### ISSUE TITLE
Error when saving a model that includes a layer_dense_features

### ISSUE THREAD

**Issue by sgvignali** [rstudio/keras#1163]
I don't know if this is the right place, but the error occurs when the model has a `layer_dense_features`.

There was already an issue opened in the **tfdatasets** repository: https://github.com/rstudio/tfdatasets/issues/53
but given that it involves functions developed in **keras** I thought to open an issue also here.

Please find all the explanations in the issue posted in **tfdatasets**, complete of reproducible examples.
To resume the following error is raised when saving a model that includes feature specifications:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'NoneType' object has no attribute 'get' 
```

No matter which function is used: `save_model_tf(), save_model_hdf5(), or serialize model()`, this error is always raised.
This morning I figured out that it's caused by the specification of the `normalizer_fn` argument in a `step_numeric_column`. If removed, the model can be saved  correctly.

I hope somebody has the time to look at it, it would be important to be able to save a model that includes feature specifications.
Thanks,
Sergio

**Comment by dfalbel** [comment]
Unfortunately there's no simple way to fix it because there's no way for TensorFlow to know how to serialize the normalizer function.

[This PR](https://github.com/rstudio/tfdatasets/pull/82) allows you to save and reload a spec. So in theory, you are able to save the model weights and the spec separately and them recreate the model and reload the weights.
