### ISSUE TITLE
BiLSTM giving weird error on R 

### ISSUE THREAD

**Issue by farahnasreen100** [rstudio/keras#1266]
Hi,
I am trying to perform text classification using BiLSTM in R. This is the code that I have used to run the model:
```
model <- keras_model_sequential()

model %>%
  layer_embedding(input_dim = max_features, output_dim = 32) %>% 
  layer_lstm(units = 32, return_sequences = TRUE) %>% 
  layer_lstm(units = 32, return_sequences = TRUE) %>% 
  bidirectional(layer_lstm(units = 32)) %>% 
  layer_dense(units = 1, activation = 'softmax')

summary(model)

```
and then the compilation and the fit of the model:
```
model %>%
  compile(loss = 'categorical_crossentropy',
          optimizer = 'adam',
          metrics = 'accuracy')

history <- model %>% 
  fit(x.train,
      y.train,
      epochs = 20,
      validation_split = 0.2)

plot(history)
```

weirdly, every time I run fit(), I get the following error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) : ValueError: in user code: C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\keras\engine\training.py:853 train_function * return step_function(self, iterator) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\keras\engine\training.py:842 step_function ** outputs = model.distribute_strategy.run(run_step, args=(data,)) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:1286 run return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:2849 call_for_each_replica return self._call_for_each_replica(fn, args, kwargs) C:\Users\farah\AppData\Local\R-MINI~1\envs\R-RETI~1\lib\site-packages\tensorflow\python\distribute\distribute_lib.py:3632 _call_for_each_replica return fn(*args, **kwargs)
```

I am not sure what I have done wrong, and the error does not prove to be very helpful either. I would appreciate any help that could be provided on how I can make this work. Thank you!

**Comment by t-kalinowski** [comment]
Hi,

Thanks for filing. Some notes:

+  There isn't really enough information in your issue for me to reproduce the issue. 
Ideally you can provide a snippet of code that I can run to reproduce the error message. `dput()` is helpful for serializing (small) objects as data, and `reprex::reprex()` is helpful for making sure your code snippet is reproducible.

+  It's on the TODO list (#1255) to improve error messages. Unfortunately the default error message that you included in your snippet is not that useful. When the error message originates from python, a good strategy is to call this to get a better sense of what is going on:
```R
reticulate::py_last_error()
cat(reticulate::py_last_error()$message)
```

+  Most bugs like this are due to shape mismatches somewhere. A good first step is to call `str` or `dim` on the values you are providing to `fit()`
