### ISSUE TITLE
Question: How to train with sample_weight

### ISSUE THREAD

**Issue by page1** [rstudio/keras#159]
I'm interested in taking advantage of `sample_weight` in the `fit` function but can't find documentation on how to use it. 

When I pass `sample_weight = rep(1, length(y_train))` I receive:
```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'list' object has no attribute 'shape' 
``` 
Any idea how to get this working?

**Comment by jjallaire** [comment]
It looks like we neglected to cast lists/vectors to array before forwarding to the underlying Keras `fit()` function. This is fixed on master here: https://github.com/rstudio/keras/commit/0093c849473e8b746126f3c5703abfc7307ae22b

If you can't install from master then this should provide a local fix:

```r
sample_weight = as.array(rep(1, nrow(x_train)))
```

Also, it's supposed to be the same length as `x` so note I used `x_train` rather than `y_train`.

**Comment by page1** [comment]
Thanks @jjallaire for the quick solution. The as.array cast is working.

**Comment by faltinl** [comment]
Since my attempts to train a multi-output model (under Keras Functional API) using the `class_weight`  option didn't succed at all (neither an error message, nor any noticable influence of any given weights on the outcome), I am trying the option `sample_weight` instead.

A first try (`samplweights` being `num [1:3000, 1] 0.4617 0.0683 0.0683 ...`, corresponding to a training length of 3000)  using the expression 

`sample_weight = samplweights`

in the paraameter list of `fit(...)` produces the error message

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  TypeError: The model has multiple outputs, so `sample_weight` should be either a list or a dict. Provided `sample_weight` type not understood: [[0.46175535]
 [0.06826814]
 [0.06826814]
 ...
 [0.06826814]
 [0.06826814]
 [0.46175535]]   

So I changed the expression (again, `samplweights` being `num [1:3000, 1] ...`, as above)   to

` sample_weight = list("outpt3"=samplweights, "outpt4"=samplweights, ...)`

just to produce the next error message

Error in py_call_impl(callable, dots$args, dots$keywords) : 
  Matrix type cannot be converted to python (only integer, numeric, complex, logical, and character matrixes can be converted 

**And this error message remains exactly the same** when `samplweights` converted to a numerical vector, i.e. as `num [1:3000] ...`, or, by means of `array_reshape()`, `num [1:3000(1d)] ...` is being used. Now I am at a loss what to do. 

Any idea and/or suggestion would be welcome - tnx in advance.
