### ISSUE TITLE
Casting internally would be nice. But here's a hot fix.

### ISSUE THREAD

**Issue by page1** [rstudio/keras#163]
If you try and create a custom metric like this:
```
K <- backend()
metric_mse <- function(y_true, y_pred) {
  return(K$mean(K$square(y_pred + -y_true), axis = 1))
}
```

you will get:
```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: TypeError: Value passed to parameter 'reduction_indices' has DataType float32 not in list of allowed values: int32, int64. 
```

To hot fix you need to cast the axis
```
K <- backend()
metric_mse <- function(y_true, y_pred) {
  return(K$mean(K$square(y_pred + -y_true), axis = 1L))
}
```

It would be great if the types "just worked"

**Comment by jjallaire** [comment]
That's a general problem with using the lower-level interfaces (they are typed whereas numeric types in R generally "just work"). At the higher levels we "do the right thing" but it's not so easy at the lower levels where you are talking directly to TF / NumPy / etc. Our approach to date has been to teach users about the type requirements rather than trying to wrap potentially hundreds of functions to do this for people. I agree not a great state of affairs.

**Comment by page1** [comment]
Sounds good.

**Comment by meliscicek** [comment]
axis=1L gives error also

**Comment by jjallaire** [comment]
I don't get the error for axis=1L

Also, we've now created R native wrappers for all backend functions, so you can write the function like this:

```{r}
metric_mse <- function(y_true, y_pred) {
  k_mean(k_square(y_pred + -y_true), axis = 2)
}
```

Note that the axis is now 2 rather than 1 (since the R native functions use 1-based rather than 0-based indexing)
