### ISSUE TITLE
Combining class weights with re-balanced classes

### ISSUE THREAD

**Issue by alanault** [rstudio/keras#248]
Hi,

I'm not clear from the documentation on the correct way to approach unbalanced classes.

I have a class split of approx 80:20 and currently, I pass a list of `class_weight` based on the training class ratio to `fit`, as the man files says:  _"for weighting the loss function"_.

However, I've found my results are skewed towards the majority class. If I rebalance the input data using upsampling (so in effect the network gets more epochs of the under-represented class), then I'm skewed more strongly towards the minority class.

Is using both upsampling _and_ weights confusing Keras, or is using both the best practice?

Many thanks
Alan

**Comment by faltinl** [comment]
Hi,-
I am observing a similar, if not the same problem, with just 1 output but 3 very asymmetric classes from a network with loss function `loss = "categorical_crossentropy"`. If I specify `loss_weights = c(1/12, 1/165, 1/23)`, corresponding to the estimated inverse frequencies of the 3 classes, I get an error message like

> ...When passing a list as loss_weights, it should have **one entry per model output**. The model has 1 outputs, but you passed loss_weights= [0.0833, 0.00606, 0.04347]

Similarly, specifying `weighted_metrics = c(1/12, 1/165, 1/23)`, there comes the error message

> ...Could not interpret metric function identifier:', [0.0833, 0.00606, 0.04347]

The documentation as well as the resources I could find elsewhere are not very informative, so, please, any further help would be highly appreciated.

Thanks in advance,
Leo

**Comment by jjallaire** [comment]
Using the `c` function might end up passing an array rather than a list. What happens if you use the `list` function instead? (e.g. `loss_weights = list(1/12, 1/165, 1/23)`)

If that doesn't work please provide a fully working version of the code that exhibits the error and I'll investigate further.

**Comment by faltinl** [comment]
Hi,-
thanks for your suggestions! Indeed, in the meantime I found a series of posts where the same problem ist discussed for Keras in Python, see in particular Answer 40 in https://datascience.stackexchange.com/questions/13490/how-to-set-class-weights-for-imbalanced-classes-in-keras .
Parallel to that I found in R documentation, `fit {keras}` ,"Train a Keras model", the same hint to use class_weigth as a named list in the parameters of `fit()`. And that's what I did: I define a named list with my estimated `class_weight`-parameters like

> `pwr <- 0.125
class_weight = list("0"=(1/12)^pwr, "1"=(1/165)^pwr, "2"=(1/23)^pwr)
` 
and this works. The scalar parameter `pwr` is used for manual tuning the separating power of the 3 classes, just by inspecting the resulting 3-class confusion matrix and mximising the sum of its diagonal elements.
I found out to be necessary not only to use a named list, but the names MUST correspond to thee class names. Otherwise an error message like 

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: `class_weight` must contain all classes in the data. The classes {0, 1, 2} exist in the data but not in `class_weight`.
is returned. I must confess that I have no idea to find out the name of my classes - it was by pure chance that I chose the numbers "0", "1" and "2". They seem to be defined by the `compile`-statement `loss = "categorical_crossentropy"`.

**Comment by jjallaire** [comment]
Okay, great, I'm glad that you got it to work!

**Comment by faltinl** [comment]
Btw - `loss_weights` are a parameter in `compile()`, and only applicable in case of multiple outputs, not for single *multiple-class* outputs.

**Comment by pablo14** [comment]
This may help: https://stackoverflow.com/questions/46907881/how-to-set-class-weight-in-keras-package-of-r/52123775#52123775

**Comment by faltinl** [comment]
Sorry to reopen this thread again after such a long time. I used the above mentioned expression 

> class_weight = list("0"=1/12, "1"=1/165, "2"=1/23) 

from time to time in `fit()` to successfully rebalance unequally distributed classes when training single output models. In the meantime, Keras has been updated to v2.3.0.0 and when I try to apply the same expression again under similar conditions I keep getting the error message

> Error in py_call_impl(callable, dots$args, dots$keywords) : 
>     ValueError: `class_weight` is only supported for Models with a single output.

The model I'm using, based on the Keras Functional API, definitely **is** a single output one, as it is defined per

> ...
> model <- keras_model(inputs = inpt, outputs = outpt) 
> LRate <- 0.00005  
> losslist <- list(outpt = 'kullback_leibler_divergence')
> metlist <- list(outpt = 'accuracy')
> model %>% compile(optimizer_adam(lr = LRate), 
>                   loss = losslist,
>                   metrics = metlist)

I would be grateful for any hint as to get rid of this problem.
