### ISSUE TITLE
LIME with Functional API

### ISSUE THREAD

**Issue by bswrundquist** [rstudio/keras#276]
Would like to use the [LIME](https://github.com/thomasp85/lime) package for feature analysis like in the example [here](https://tensorflow.rstudio.com/blog/keras-customer-churn.html).

In the example they are using the Sequential API which has a class attribute keras.models.Sequential which is modified for LIME to use. The Functional API model does not seem to have something usable in the same sense as the sequential API for the LIME package.

```
inputs <- layer_input(shape = c(784))
predictions <- inputs %>%
 layer_dense(units = 1, activation = 'softmax')
model <- keras_model(inputs = inputs, outputs = predictions)
class(model)
```
[1] "keras.engine.training.Model"     
[2] "keras.engine.topology.Container" 
[3] "keras.engine.topology.Layer"     
[4] "python.builtin.object"      

`class(keras_model_sequential())`
[1] "keras.models.Sequential"         
[2] "keras.engine.training.Model"     
[3] "keras.engine.topology.Container" 
[4] "keras.engine.topology.Layer"    
[5] "python.builtin.object"

**Comment by jjallaire** [comment]
Why not just use the class `keras.engine.training.Model`, e.g. `predict_model.keras.engine.training.Model`

**Comment by jjallaire** [comment]
Looks good!

**Comment by Fabister** [comment]
In this example (and with any other) I keep getting the error `invalid 'dimnames' given for data frame`, which should actually be dealt with by using `data.frame(data)` in `explainer <- lime::lime(...)` and `explanation <- lime::explain(...)` ([see also](https://stackoverflow.com/questions/59072918/invalid-dimnames-given-for-data-frame-when-using-lime-on-a-keras-cnn-model-in)). Any ideas why this is the case?

Follow up question to the example in the [link](https://stackoverflow.com/questions/59072918/invalid-dimnames-given-for-data-frame-when-using-lime-on-a-keras-cnn-model-in) mentioned: What is the exact difference when using `model_type.keras.engine.sequential.Sequential` and `predict_model.keras.engine.sequential.Sequential` instead of `model_type.keras.engine.training.Model` and `predict_model.keras.engine.training.Model`?

_Using R 3.6.3, lime 0.5.1, keras 2.3.0, tensorflow 2.2.0, tfruns 1.4_
