### ISSUE TITLE
Running Keras on a (Spark) cluster

### ISSUE THREAD

**Issue by nutle** [rstudio/keras#321]
Is it possible to run Keras on (any) cluster? If so, what are the possibilities? 

I.e., for python yahoo made a wrapper to run TensorFlow on a Spark cluster by [TensorFlowOnSpark](https://github.com/yahoo/TensorFlowOnSpark/). Is something similar possible from Rstudio's perspective? If not, I'd also be interested in possible hacks/workarounds for it.

Thanks!

**Comment by jjallaire** [comment]
We don't currently support although we'd certainly like to.

We do have the tfdatasets package (https://tensorflow.rstudio.com/tools/tfdatasets/articles/introduction.html) which has facilities for sharding and streaming input files. However, this currently just works with native distributed tensorflow / CloudML, and requires that you re-write your preprocessing code using TF graph operations (we'd also like to make this much higher level so you keep all preprocessing code in R and still benefit from the higher performance access to data).

**Comment by nutle** [comment]
To make it clear, this issue was closed because the support is here/soon, or you ditched this idea entirely?

**Comment by jjallaire** [comment]
The only way to do this right now is using tfdatasets (to shard data) and cloudml (to create and utilize a cluster). This is *in principle* as we don't yet have working examples of how to do this. The trickiest part as I said previously is converting all of your preprocessing code to be done using `dataset_map()` / `dataset_filter()`. I guess another way would be doing all of the preprocessing offline and just writing tfrecords into Google Storage buckets.

So that's the way that's currently supported. We haven't yet had the time (or candidly demand from users) to implement e.g. a Spark based solution.
