### ISSUE TITLE
Support specifying the number of workers to use in predict_generator

### ISSUE THREAD

**Issue by martinstuder** [rstudio/keras#347]
See `predict_generator` at https://keras.io/models/model/#methods:
`predict_generator(self, generator, steps=None, max_queue_size=10, workers=1, use_multiprocessing=False, verbose=0)`

`workers` specifies the maximum number of processes to spin up. Being able to specify multiple workers is very useful to perform image preprocessing and/or data augmentation on multiple CPUs and keep the GPU busy.

**Comment by jjallaire** [comment]
Added support for the `workers` parameter here: https://github.com/rstudio/keras/commit/63450c19b7eb84aa4aedce96b2d9a3c43cc9ac53

Note that this will only work for Keras native generators (e.g. `flow_images_from_directory()`) since R based generators must run on the main thread. Note also that this uses Python threading rather than multiprocessing (since there are other issues w/ using multiprocessing with the R Python interface)
