### ISSUE TITLE
predict() for image larger than used in training

### ISSUE THREAD

**Issue by fabien-w** [rstudio/keras#350]
Hi,

I am using the get_unet_128 model from the rstudio keras examples in linux [here](https://keras.rstudio.com/articles/examples/unet_linux.html)
The function predict() works with the model for image of size 128 x 128 , however i don't manage to make prediction with this model on larger image (i.e. 2048 x 2048). For remote sensing applications, it's important as i dont want to cut all images that will be used only for prediction in small tiles. One [issue](https://github.com/keras-team/keras/issues/3267) is related to this in keras but the parameter check_input_shapes of the python function predict() does not exist in the r function predict(). 

the error message is : 
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Error when checking : expected input_1 to have shape (128, 128, 3) but got array with shape (2048, 2048, 3) 

Any help is welcome !

Thank you very much,

Fabien

**Comment by jjallaire** [comment]
The Python version of `predict` does not in fact have a `check_input_shapes` argument, see the docs here: https://keras.io/models/model/#predict. The discussion you references was merely someone asking for this but the issue was closed since feeding images to a model of a size distinct from that which it is trained on isn't really practical. If you want to do prediction on larger images you either need to train on larger images or you need to slice up the large images into a set of smaller ones.

**Comment by fabien-w** [comment]
Ok, thank you very much for your answer. For my case using larger images is not a good solution as it will drastically reduce my sampling for training. I will choose the second option !

**Comment by jjallaire** [comment]
Okay, great. Glad you have got a workable approach!

**Comment by fabien-w** [comment]
Hi,
I have found another solution which is more convenient. 
if you have rgb 128*128 pixels image for training and rgb 256 * 256 pixels image for prediction, just reload your model after training changing the size of inputs shape from inputs <- layer_input(shape =  c(128, 128, 3)) to inputs <- layer_input(shape =  c(256, 256, 3)), load the weight and then you can predict for 256*256 pixels rgb images.
that's work for me !
