### ISSUE TITLE
Custom loss function for Weibull log-likelihood

### ISSUE THREAD

**Issue by phareskrad** [rstudio/keras#354]
Hi,

I'm trying to convert the python loss function from this repo:
https://github.com/daynebatten/keras-wtte-rnn

```
weibull_loglik_discrete = function(y_true, y_pred) {
  K = backend()
  y_true = K$eval(y_true)
  y_pred = K$eval(y_pred)
  y_ = y_true[, 1]
  u_ = y_true[, 2]
  a_ = y_pred[, 1]
  b_ = y_pred[, 2]

  hazard0 = ((y_ + 1e-35) / a_) ^ b_
  hazard1 = ((y_ + 1) / a_) ^ b_

  return(K$constant(-1 * mean(u_ * log(exp(hazard1 - hazard0) - 1.0) - hazard1), dtype = 'float', shape = 1))
}

weibull_activate = function(ab) {
  a = k_exp(ab[, 1])
  b = k_softplus(ab[, 2])
  
  a = k_reshape(a, c(length(a), 1))
  b = k_reshape(b, c(length(b), 1))
  
  return(k_concatenate(list(a, b)))
}

model = keras_model_sequential()
model %>%
  layer_dense(units = 612, activation = 'relu', input_shape = c(1087)) %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 256, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.2) %>%
  layer_dense(units = 2) %>%
  layer_activation(activation = weibull_activate, name = 'weibull_activation') %>%
  compile(
    loss = weibull_loglik_discrete,
    optimizer = optimizer_rmsprop(lr=.001)
  )
```

The model compiles well until the last step of compiling the custom loss function into it, it gives me error message like this:

```
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  RuntimeError: Evaluation error: InvalidArgumentError: You must feed a value for placeholder tensor 'weibull_activation_target' with dtype float and shape [?,?]
	 [[Node: weibull_activation_target = Placeholder[dtype=DT_FLOAT, shape=[?,?], _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op 'weibull_activation_target', defined at:
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 821, in compile
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/training.py", line 755, in compile
    dtype=K.dtype(self.outputs[i]))
  File "/usr/local/lib/python3.5/dist-packages/keras/backend/tensorflow_backend.py", line 497, in placeholder
    x = tf.placeholder(dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 1680, in placeholder
    return gen_array_ops._placeholder(dtype=dtype, shape=shape, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflo 
```

I found one related issues https://github.com/rstudio/keras/issues/193 about creating custom loss function, but it seems like the problem didn't really get solved, any suggestion here?  

Thanks for any help!

**Comment by jjallaire** [comment]
Yes, I think the problem is that we can't currently slice tensors with unknown dimensions. If specifying the dimensions with `k_exp(ab[, 1])` is merely a convenience (i.e. you actually have a way of knowing the size of the first dimension) then you could probably work around the problem by using static dimensions.

**Comment by phareskrad** [comment]
@jjallaire Not sure if I understand correctly, but I tried to specify the input size with fixed batch size, and explicitly reshape the y_true and y_pred in the loss function, still got the same error message

```
weibull_loglik_discrete = function(y_true, y_pred) {
  K = backend()
  y_true = k_reshape(y_true, c(1024, 2))
  y_pred = k_reshape(y_pred, c(1024, 2))
  browser()
  y_true = K$eval(y_true)
  y_pred = K$eval(y_pred)
  
  y_ = y_true[, 1]
  u_ = y_true[, 2]
  a_ = y_pred[, 1]
  b_ = y_pred[, 2]

  hazard0 = ((y_ + 1e-35) / a_) ^ b_
  hazard1 = ((y_ + 1) / a_) ^ b_

  return(K$constant(-1 * mean(u_ * log(exp(hazard1 - hazard0) - 1.0) - hazard1), dtype = 'float', shape = 1))
}

weibull_activate = function(ab) {
  a = k_exp(ab[, 1])
  b = k_softplus(ab[, 2])
  
  a = k_reshape(a, c(length(a), 1))
  b = k_reshape(b, c(length(b), 1))
  
  return(k_concatenate(list(a, b)))
}
model = keras_model_sequential()
model %>%
  layer_dense(units = 612, activation = 'relu', batch_input_shape = c(1024, 1087), dtype = 'float') %>% 
  layer_dropout(rate = 0.4) %>% 
  layer_dense(units = 256, activation = 'relu') %>%
  layer_dropout(rate = 0.3) %>%
  layer_dense(units = 128, activation = 'relu') %>%
  layer_dropout(rate = 0.2) %>%
  layer_dense(units = 2) %>%
  layer_activation(activation = weibull_activate, name = 'weibull_activation') %>%
  compile(
    loss = weibull_loglik_discrete,
    optimizer = optimizer_rmsprop(lr=.001)
  )
``` 

And specifically it is this line throwing error:
```
y_true = K$eval(y_true)
```

**Comment by jjallaire** [comment]
Okay, right. You can't actually evaluate tensors passed into these functions because when TF graphs are being constructed the values are placeholders. So if you want to slice the tensors you can do that but need to use explicit dimension sizes. Interestingly, we are actually discussing how to add support for slicing tensors with unknown dimensions here: https://github.com/rstudio/tensorflow/issues/230

**Comment by phareskrad** [comment]
Ok I see, but the next problem is I want to compute
```
hazard0 = ((y_ + 1e-35) / a_) ^ b_
```
And the **k_pow** only accept second arg as integer, unlike the **k.pow** in Python, is this something I could get around?

**Comment by phareskrad** [comment]
Ah, now this compiles:
```
weibull_loglik_discrete = function(y_true, y_pred) {
  K = backend()
  y_true = k_reshape(y_true, c(1024, 2))
  y_pred = k_reshape(y_pred, c(1024, 2))
 
  y_ = y_true[, 1]
  u_ = y_true[, 2]
  a_ = y_pred[, 1]
  b_ = y_pred[, 2]

  hazard0 = ((y_ + 1e-35) / a_) ^ b_
  hazard1 = ((y_ + 1) / a_) ^ b_

  return(-1 * k_mean(u_ * k_log(k_exp(hazard1 - hazard0) - 1.0) - hazard1))
}
```

Thanks for the help!

**Comment by jjallaire** [comment]
Great, glad this works! I also made a change to `k_pow()` so it now can accept tensor arguments.

**Comment by diegoperoni** [comment]
Hi @jjallaire ,

I have a similar problem perhaps you can help me :-)
My function make differencing (y_t - y_t0) so I start with 1024 elements (batch_size) but at the end I have just 1023 elements to calculate return.
The error message indicate me that it needs 2014, I don't understand why: the function must return a just scalar....
Thanks in advance for your help

tradingReturn = function(y_true, y_pred) {
  K = backend()
  y_true_log = k_log(y_true)
  y_pred_log = k_log(y_pred)
  y_true_diff = y_true_log[2:batch_size] - y_true_log[1:(batch_size-1)]
  y_pred_diff = y_pred_log[2:batch_size] - y_pred_log[1:(batch_size-1)]
  y_true_diff = k_reshape(y_true_diff, (batch_size-1))
  y_pred_diff = k_reshape(y_pred_diff, (batch_size-1))
  return (k_sum( -(k_sign(y_pred_diff) * y_true_diff) ))
}


 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Input to reshape is a tensor with 1024 values, but the requested shape has 1023
	 [[Node: loss_19/dense_2_loss/Reshape = Reshape[T=DT_FLOAT, Tshape=DT_INT32, _device="/job:localhost/replica:0/task:0/device:CPU:0"](loss_19/dense_2_loss/Sub, loss_19/dense_2_loss/Reshape_1/shape)]]

Caused by op u'loss_19/dense_2_loss/Reshape', defined at:
  File "/home/peroni/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/models.py", line 863, in compile
    **kwargs)
  File "/home/peroni/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 830, in compile
    sample_weight, mask)
  File "/home/peroni/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/keras/engine/training.py", line 429, in weighted
    score_array = fn(y_true, y_pred)
  File "/usr/lib64/R/library/reticulate/python/rpytools/call.py", line 13, in python_function
    res = rpycall.call_r_function(f, *args, **kwargs)
  File "/home/peroni/.virtualenvs/r-tensorfl
