### ISSUE TITLE
ERROR: dependency 'processx' is not available for package 'tensorflow'

### ISSUE THREAD

**Issue by vrishaligiri** [rstudio/keras#39]
**Command : devtools::install_github("rstudio/keras")**

Downloading GitHub repo rstudio/keras@master
from URL https://api.github.com/repos/rstudio/keras/zipball/master
Installing keras
Downloading GitHub repo rstudio/tensorflow@master
from URL https://api.github.com/repos/rstudio/tensorflow/zipball/master
Installing tensorflow
"C:/PROGRA1/MIE74D1/RCLIEN1/R_SERVER/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/../AppData/Local/Temp/RtmpUrkTr6/devtools1d1c25a770c6/rstudio-tensorflow-8795bd8"  \
  --library="C:/Users/../Documents/R/win-library/3.3" --install-tests 

**ERROR: dependency 'processx' is not available for package 'tensorflow'
removing 'C:/Users/girivr/Documents/R/win-library/3.3/tensorflow'
Error: Command failed (1)**

**Comment by jjallaire** [comment]
The problem is that your CRAN repository (provided by MRAN: https://mran.microsoft.com/) doesn't have processx available yet (because it uses an snapshot of CRAN rather than the current CRAN). You can either configure MRAN to allow you access to the current state of CRAN (not sure how this is done though) or you can install processx from GitHub via:

```r
devtools::install_github("r-lib/processx")
```
