### ISSUE TITLE
So much time to install

### ISSUE THREAD

**Issue by LeitchP** [rstudio/keras#436]
After a day of troubleshooting, I managed to get this installed on my RStudio running Microsoft Open R.  Issues included: 
RStudio came with a non-compatible version of jsonlite (the default for RStudio), which mandated a new install of the package, which was blocked if running RStudio (even when trying to restart R session multiple times).  I had to run this from the server location (with RStudio closed)

C:\Program Files\Microsoft\R Client\R_SERVER\bin\x64>
install.packages('jsonlite', dependencies=TRUE, repos='http://cran.rstudio.com/')

I ran it through rscript.

There were a lot of other items that wouldn't install either, 
rtools 3.3.2
Rcpp,
curl
swirl
r-lib/zeallot
tidyverse/glue
r-lib/rlang
tidyverse/tidyselect
rstudio/tfruns
r-lib/processx
rstudio/reticulate

even devtools::install_deps(dependencies = TRUE)

It would have been really nice to have been able to run the "simple instructions" that worked first go on the current release of RStudio and Microsoft Open R. This one was a battle.

**Comment by LeitchP** [comment]
I forgot to add that all of this install required RTools 3.3, 3.4 and 3.5, all of which attempt to install at a variety of locations across my HDD.

I realise that the "root cause" of this is probably my specific mode of using RStudio with Microsoft Open R, and that apparently, the base build for R had jsonlite set as the wrong version.  Perhaps this is the wrong place to note these install issues, however this is the default install on Microsoft Azure Data Science VMs (Windows and Linux).

Steps to reproduce:
1) Install R Studio and Microsoft Open R
2) attempt to install keras.

Thank you.

**Comment by jjallaire** [comment]
The issue with older versions of packages being the default on Microsoft R Open is a hard one for package developers to circumvent (as we can update CRAN but we can't update MRAN b/c it's a frozen snapshot). We are regularly making changes to our packages in response to changes in Keras/TensorFlow/Python/pip/conda, etc. and as a result systematically running older versions of these packages is a recipe for difficulties. 

R Tools installation is pretty foolproof/automated for RStudio with CRAN R (and always installs to the same C:\RBuildTools directory. It may be that Microsoft R Open should try to set that up in advance for users so that they don't have to navigate the issues which you did.

**Comment by jjallaire** [comment]
The problem is that Microsoft Open R is a moving target (every release pins
a different variation of CRAN). I don't think it's a fair burden for
package maintainers to need to track every release of a a 3rd-party
derivative of CRAN R which fundamentally changes the semantics of package
distribution/updating.

**Comment by LeitchP** [comment]
I fundamentally agree with you, which is why I called this out to start with.  Further to that point, one of the packages noted that the latest CRAN R installed an old version, and they had no direct control over the version CRAN R uses.  

In short, what would be helpful is a complete list of prerequisites with their versions.  This isn't a necessity but a nicety.  It may not even be practical, however it was the reason for my post, along with all the packages I could find in my browser history in case I, or anyone else, wishes to install Keras on Microsoft open R.
