### ISSUE TITLE
use fit_generator

### ISSUE THREAD

**Issue by zaccliu** [rstudio/keras#57]
Is there a concrete example of using fit_generator in rstudio/keras? It requires to provide a generator and I don't know if it is possible to write a generator in R. Any suggestions would be appreciated.

**Comment by jjallaire** [comment]
It's currently not possible to write a generator in R. This is because `fit_generator` uses Python multi-threading / multi-processing, which doesn't play well with R code. The function is included for use with the "built-in" generators like `flow_images_from_directory`.

If you want to stream training data right now the best way to do that is with the `train_on_batch` function.

**Comment by jjallaire** [comment]
Docs updated here: https://github.com/rstudio/keras/commit/f50a62bd0c4374a7292a78282758e45d494e2d38

**Comment by zaccliu** [comment]
Thank you, jjallaire. Then we will not be able to use "callback" option when using train_on_batch, right? The option gives the nice features, like saving the best model.

**Comment by jjallaire** [comment]
You don't need callbacks per-se since they are only called at the beginning/end of batches and epochs (where you are able to inject code anyway since you are running the training loop). Put another way, callbacks are there mostly so you can inject code into the training loop. When you are running your own training loop you can include code that does whatever you need.

In terms of using existing callbacks like `callback_model_checkpoint` it seems like you could create it and then call it manually. Something like this (lots of details to fill in here, this is just intended to point you in the right direction):

```r
checkpoint_cb <- callback_model_checkpoint(..)
checkpoint_cb$set_params(...)
checkpoint_cb$set_model(...)
checkpoint_cb$on_epoch_end(1)
```

**Comment by zaccliu** [comment]
got it. Thanks very much!

**Comment by jjallaire** [comment]
I've figured out how to surmount the threading issues so you can now write custom generators in R. Documentation is here: https://rstudio.github.io/keras/articles/faq.html#how-can-i-use-keras-with-datasets-that-dont-fit-in-memory
