### ISSUE TITLE
Error: ImportError: No module named api.types

### ISSUE THREAD

**Issue by saanasum** [rstudio/keras#653]
Installation of keras worked in R. However, when I try to load mnist dataset the following error occurs:

```R
> library("keras")
> mnist <- dataset_mnist()
Using TensorFlow backend.
/home/xxx-removed-xxx/.virtualenvs/r-tensorflow/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Error: ImportError: No module named api.types
```

P.S.:
```R
> install.packages("r-tensorflow")
Installing package into ‘/home/xxx-removed-xxx/R/x86_64-pc-linux-gnu-library/3.5’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘r-tensorflow’ is not available (for R version 3.5.2)
```

**Comment by skeydan** [comment]
Hello to everybody on this thread,

if you still have problems using `install_tensorflow()` from RStudio, please try again now.

First install `tensorflow` directly from GitHub, as in 

```
devtools::install_github("rstudio/tensorflow")
devtools::install_github("rstudio/keras")
```

Then do 

```
tensorflow::install_tensorflow()
tensorflow::tf_config()
```

which should give you version 1.12.

We have been installing TF 1.10 until yesterday because of a bug in that will only be fixed in TF 1.13 (which should be out anytime but unfortunately isn't yet). Now with people having installation problems due to incompatibilities with `numpy` as installed by `conda`, we decided to switch to TF 1.12 now and as soon as TF 1.13 is actually available, we'll install that by default.

Thanks for reporting the problem!

If you still run into problems installing, please open another issue and describe the problem, indicating the output of  

```
reticulate::py_discover_config()
reticulate::use_condaenv("r-tensorflow")
reticulate::py_config()
```

 Thanks!
