### ISSUE TITLE
error installing tensorflow GPU

### ISSUE THREAD

**Issue by bmitre** [rstudio/keras#667]
**_I tried the following code and got the following error. Can anybody help, please? Thank you._**

> install_tensorflow(version="gpu")
Creating r-tensorflow conda environment for TensorFlow installation...
Solving environment: ...working... failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/main/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/main/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Error: Error 1 occurred creating conda environment r-tensorflow

**Comment by henry090** [comment]
Hi, which version of Anaconda do you use? 32bit or 64bit? 32 bit worked fine for me.
In addition, look at [here](https://github.com/conda/conda/issues/6064#issuecomment-450585312)

**Comment by avidalfinsa** [comment]
Hi,
I've got the same problem.

> version
               _                           
platform       x86_64-w64-mingw32          
arch           x86_64                      
os             mingw32                     
system         x86_64, mingw32             
status                                     
major          3                           
minor          5.2                         
year           2018                        
month          12                          
day            20                          
svn rev        75870                       
language       R                           
version.string R version 3.5.2 (2018-12-20)
nickname       Eggshell Igloo

And i've got conda 4.6.4 preinstalled for all users and included in the PATH. 

`keras::install_keras()` worked
`keras::install_keras(version = "gpu)` didn't work with the same error

The problem seems to be that general conda envs are in 

> C:/Users/user/.conda/envs

while the envs created by R are in 

> C:/Users/user/Documents/.conda/envs

So R doesn't see general envs and it is not possible also to change the env with `use_condaenv(condaenv = "dlwin", required = TRUE)`

I solved it by copying my own preconfigured gpu tensorflow env from `/.conda/envs` to `/Documents/.conda/envs` and switching to that env.

Hope it helps. Cheers.
