### ISSUE TITLE
fix custom generator after upgrade to TF 1.13

### ISSUE THREAD

**Issue by skeydan** [rstudio/keras#682]
```
???: failure: R function can be used as custom generator
`force(expr)` threw an error.
Message: AttributeError: 'RGenerator' object has no attribute 'shape'

Detailed traceback: 
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 1426, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 115, in model_iteration
    shuffle=shuffle)
  File "/home/key/anaconda3/envs/r-tensorflow/lib/python3.7/site-packages/tensorflow/python/keras/engine/training_generator.py", line 377, in convert_to_generator_like
    num_samples = int(nest.flatten(data)[0].shape[0])
```

**Comment by skeydan** [comment]
big change to `training_generator.py` 
https://github.com/tensorflow/tensorflow/commit/8420f5741558c79fa71b442bcc613800c3b3dfa6#diff-6561418ac6882a842d78dad52731895b

**Comment by skeydan** [comment]
Anyone running into this until it's fixed, please use TF 1.12  for the moment
```
install_tensorflow(version="1.12")
```

**Comment by jjallaire** [comment]
This one is going to be tricky. It looks like they no longer accept a Python iterator as a generator, which causes us to hit a Keras codepath that is expecting a plain numpy data type.

We could get them to change this, or we could try to pass something that is acceptable (they accept lots of different things, including proper generators, a Keras "Sequence" (which I unfortunately believe requires a length which we don't have). 

Here's the S3 method where we current pass the generator back to Keras:

https://github.com/rstudio/keras/blob/master/R/model.R#L933-L935

So this might need to yield a generator instead. Note that we already synthesize generators for datasets (that code is right above the linked code), you can see the generator code here: https://github.com/rstudio/keras/blob/master/inst/python/kerastools/generator.py

@javierluraschi Could you take a look at this when you have time? In the meantime, I wonder if we need to continue to point users to 1.12 since this will break a meaningful amount of end user code.

**Comment by skeydan** [comment]
Thanks JJ! We'll take a look with Javier later today...
As a very simple start, I tried adding in `kerastools` a `gen.py` (which should be a Python generator):

```
def g(x):

  def gen():
    while 1:
      yield x()

  return gen()
```

and then this would be called from `model.R`

```
as_generator.function <- function(x) {
  python_path <- system.file("python", package = "keras")
  tools <- reticulate::import_from_path("kerastools", path = python_path)
  tools$gen$g(x)
}
```

This doesn't take care of the format of the returned values of course, but in a prototypical way, would this be what we'd want to do?

**Comment by jjallaire** [comment]
Yes, something like that. Although you have to run it through the call to `reticulate::py_iterator()` (as we currently do) since that takes care of some threading issues (basically, the generator is called on a background thread which is a no-no for R, so `py_iterator` marshalls calls to the foreground thread). So the wrapper function you write will need to call the iterator `next()` rather than calling the R function directly.

**Comment by jjallaire** [comment]
I have changed the default version of tensorflow we install to 1.12 pending a fix to this issue: https://github.com/rstudio/tensorflow/commit/dd2249089e11a466fdce88f275847f0fa2f8f17b

This PR provides a partial fix for this issue: https://github.com/rstudio/keras/pull/692

With this PR, the generator is successfully passed to keras, but training fails with this error:

```
UnboundLocalError: local variable 'a' referenced before assignment
```

Which is the same error being reported by another user here: https://github.com/rstudio/keras/issues/33#issuecomment-470490670

@javierluraschi I have a feeling this may result in a PR back into TF as the stack leads pretty far into core tensorflow. Could you take a look at this issue and see if there is something we can do on our end? (and failing that a PR we can put into TF that will fix it on their end).

**Comment by MaximilianPi** [comment]
I stumbled about the same issue and solved it with tf$data. Here's a snippet of my vae code:

``
path = tf$data$Dataset$from_tensor_slices(files)
image = path$map(preprocess_function, num_parallel_calls=10L)
AUTOTUNE = tf$data$experimental$AUTOTUNE

image_gen = tf$data$Dataset$zip(reticulate::tuple(image, image))
image_gen = image_gen$shuffle(length(files))
image_gen = image_gen$'repeat'()
image_gen = image_gen$batch(256L)
image_gen = image_gen$prefetch(buffer_size = AUTOTUNE)

vae$fit(image_gen, epochs = 40L, steps_per_epoch = as.integer(length(files)/256))
```
So, the new gen function should return PrefetchDataset object.

**Comment by javierluraschi** [comment]
Not sure a workaround is feasible on our end since not passing a generator assumes the TensorFlow model has a `batch_size` which complicates this even further, so most likely, the workaround in TensorFlow 1.3 is for R/Python users to not use generators in Keras. I believe this also affects the Keras interface for Python.

I can try to look for a workaround on our end if we feel strongly that this should be enabled in 1.3; otherwise, we can wait for https://github.com/tensorflow/tensorflow/pull/26630 to get merged and recommend upgrading to a version that contains this fix.

**Comment by javierluraschi** [comment]
Actually, we should also be able to add a workaround without the fix we are proposing. This fix would fetch all the data from the generator and set the batch size. This won’t work for large dataset, but is better than breaking this API with 1.3.

**Comment by skeydan** [comment]
solved as per https://github.com/rstudio/keras/pull/692
