### ISSUE TITLE
InvalidArgumentError: Incompatible shapes: [4,1,121,1] vs. [4,1]

### ISSUE THREAD

**Issue by msloryg** [rstudio/keras#785]
When I try to fit my CNN on a linux cluster server, I produces the following error:

```
Error in py_call_impl(callable, dots$args, dots$keywords) :
  InvalidArgumentError: Incompatible shapes: [4,1,121,1] vs. [4,1]
         [[{{node training/RMSprop/gradients/loss/dense_1_loss/MeanSquaredError/sub_grad/BroadcastGradientArgs}}]]

Detailed traceback:
  File "/cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training.py", line 880, in fit
    validation_steps=validation_steps)
  File "/cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/engine/training_arrays.py", line 329, in model_iteration
    batch_outs = f(ins_batch)
  File "/cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow/python/keras/backend.py", line 3076, in __call__
    run_metadata=self.run_metadata)
  File "/cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1439, in __call__
    run_metadata_ptr)
  File "/cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status

```
I don't really know what the probem is because running it in RStudio on my own laptop works fine. This is when the error occured:
```
history <- model %>% fit(
  x_train, y_train,
  batch_size = 4,
  epochs = 30,
  verbose = 1,
  validation_split = 0.2
)
```

Here is the output of py_config(), sessionInfo() and tf_config():
```
> reticulate::py_config()
python:         /cm/shared/apps/anaconda/bin/python
libpython:      /cm/shared/apps/anaconda/lib/libpython3.6m.so
pythonhome:     /cm/shared/apps/anaconda:/cm/shared/apps/anaconda
version:        3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]
numpy:          /cm/shared/apps/anaconda/lib/python3.6/site-packages/numpy
numpy_version:  1.16.2
tensorflow:     /cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow

python versions found:
 /cm/shared/apps/anaconda/bin/python
 /usr/bin/python
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS release 6.10 (Final)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] caret_6.0-84           ggplot2_3.1.1          lattice_0.20-33
[4] abind_1.4-5            reticulate_1.12.0-9000 tensorflow_1.13.1.9000
[7] keras_2.2.4.1.9001

loaded via a namespace (and not attached):
 [1] gbm_2.1.5          tidyselect_0.2.5   reshape2_1.4.3     purrr_0.3.2
 [5] splines_3.2.3      colorspace_1.4-1   generics_0.0.2     stats4_3.2.3
 [9] base64enc_0.1-3    survival_2.38-3    prodlim_2018.04.18 rlang_0.3.4
[13] ModelMetrics_1.2.2 pillar_1.3.1       glue_1.3.1         withr_2.1.2
[17] foreach_1.4.4      plyr_1.8.4         stringr_1.4.0      lava_1.6.5
[21] timeDate_3043.102  munsell_0.5.0      gtable_0.3.0       recipes_0.1.5
[25] codetools_0.2-14   doParallel_1.0.14  pscl_1.5.2         tfruns_1.4
[29] bst_0.3-17         parallel_3.2.3     class_7.3-14       Rcpp_1.0.1
[33] mpath_0.3-12       scales_1.0.0       ipred_0.9-9        jsonlite_1.6
[37] gridExtra_2.3      stringi_1.4.3      dplyr_0.8.0.1      numDeriv_2016.8-1
[41] grid_3.2.3         tools_3.2.3        magrittr_1.5       lazyeval_0.2.2
[45] glmnet_2.0-16      tibble_2.1.1       crayon_1.3.4       whisker_0.3-2
[49] pkgconfig_2.0.2    zeallot_0.1.0      MASS_7.3-45        Matrix_1.2-3
[53] data.table_1.11.4  lubridate_1.6.0    gower_0.2.0        assertthat_0.2.1
[57] iterators_1.0.10   R6_2.4.0           rpart_4.1-10       nnet_7.3-11
[61] nlme_3.1-122
> tf_config()
TensorFlow v1.13.1 (/cm/shared/apps/anaconda/lib/python3.6/site-packages/tensorflow)
Python v3.6 (/cm/shared/apps/anaconda/bin/python)


```
I tried different batch sizes but that did not help. If more information is needed, please tell me.

**Comment by skeydan** [comment]
yes, please also provide the sessioninfo from your laptop and the model code (including the loss function).

Are `x_train` and `y_train` guaranteed to be referring to the same thing in both environments?

**Comment by msloryg** [comment]
the sessionInfo() from my laptop is:
```
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] tensorflow_1.10.0.9000   tfprobability_0.0.0.9000 countreg_0.2-1          
 [4] abind_1.4-5              mpath_0.3-7              MASS_7.3-50             
 [7] pscl_1.5.2               glmnet_2.0-16            foreach_1.4.4           
[10] Matrix_1.2-14            caret_6.0-81             ggplot2_3.1.0           
[13] lattice_0.20-35          dplyr_0.7.8             

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0          lubridate_1.7.4     class_7.3-14        assertthat_0.2.1   
 [5] zeallot_0.1.0       ipred_0.9-8         R6_2.4.0            plyr_1.8.4         
 [9] stats4_3.4.3        pillar_1.3.1        tfruns_1.4          rlang_0.3.1        
[13] lazyeval_0.2.0      rstudioapi_0.9.0    data.table_1.10.4-3 whisker_0.3-2      
[17] rpart_4.1-13        reticulate_1.11     keras_2.2.4.9001    splines_3.4.3      
[21] gower_0.2.0         stringr_1.3.1       munsell_0.5.0       compiler_3.4.3     
[25] numDeriv_2016.8-1   pkgconfig_2.0.2     base64enc_0.1-3     gbm_2.1.5          
[29] nnet_7.3-12         tidyselect_0.2.5    tibble_2.0.1        gridExtra_2.3      
[33] prodlim_2018.04.18  codetools_0.2-15    crayon_1.3.4        withr_2.1.2        
[37] recipes_0.1.4       ModelMetrics_1.2.2  grid_3.4.3          nlme_3.1-131       
[41] jsonlite_1.6        gtable_0.2.0        magrittr_1.5        scales_1.0.0       
[45] stringi_1.2.4       reshape2_1.4.3      doParallel_1.0.14   bst_0.3-17         
[49] bindrcpp_0.2.2      timeDate_3012.100   generics_0.0.2      lava_1.6.5         
[53] iterators_1.0.10    tools_3.4.3         glue_1.3.1          purrr_0.3.1        
[57] parallel_3.4.3      survival_2.41-3     yaml_2.2.0          colorspace_1.3-2   
[61] bindr_0.1.1 
```
Yes, I saved the x_train, y_train I used on my laptop in an Rda file and loaded it on the server. This is how I built the model:
```
model <- keras_model_sequential()

samples <- dim(x_train)[1]
n_rows <- dim(x_train)[2]
n_timesteps <- dim(x_train)[3]#ncols: days
n_features <- dim(x_train)[4]#channels

model %>%
  layer_conv_2d(filters = 32, kernel_size = c(3, 3), activation = "relu",
                input_shape = c(n_rows, n_timesteps, n_features)) %>%
  layer_max_pooling_2d(pool_size = c(1, 3)) %>%
  layer_dense(units = 50, activation = "relu") %>%
  layer_dense(units=1)
summary(model)

model %>% compile(
  loss = 'mse',
  optimizer = optimizer_rmsprop(),
  metrics = c('mse', 'mape')
)

```
until here everything is fine on the server.
```
# Training & Evaluation ----------------------------------------------------

# Fit model to data
history <- model %>% fit(
  x_train, y_train,
  batch_size = 4,
  epochs = 30,
  verbose = 1,
  validation_split = 0.2
)
```
the last part throws the error

**Comment by skeydan** [comment]
I see you have an older version of TensorFlow on your laptop (1.10) vs. on the server (1.13).
Can you try updating your laptop to use version 1.13, too, and see what happens?

**Comment by msloryg** [comment]
I think it is only the R-package tensorflow where I got version 1.10 (see sessionInfo() output), since the output of tf_config() on my laptop is:
```
> tf_config()
TensorFlow v1.13.1 (C:\Users\Laura\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.p)
Python v3.6 (C:\Users\Laura\AppData\Local\Programs\Python\Python36\python.exe)
```
The tensorflow version should be the same. But I can try to update the R package tensorflow on my laptop.

**Comment by skeydan** [comment]
Oh I see, yes, these should always be in sync (the R package version of `tensorflow` and the Python version reported by `tf_config()`)

**Comment by msloryg** [comment]
sessionInfo is now:
```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tensorflow_1.13.1.9000 keras_2.2.4.1.9001    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0             lattice_0.20-35        zeallot_0.1.0         
 [4] grid_3.4.3             R6_2.4.0               jsonlite_1.6          
 [7] magrittr_1.5           tfruns_1.4             whisker_0.3-2         
[10] Matrix_1.2-14          reticulate_1.12.0-9001 generics_0.0.2        
[13] tools_3.4.3            yaml_2.2.0             compiler_3.4.3        
[16] base64enc_0.1-3       
```
And yes, now I get an error on my laptop as well :( 
```
  Error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: Incompatible shapes: [4,1] vs. [4,1,121,1]
	 [[{{node metrics/mean_absolute_percentage_error/sub}}]] 
```

**Comment by msloryg** [comment]
omg I think it is because I don't use a ```layer_flatten()``` to vectorize my 3dimensional data before using the dense layers. I feel really dumb right now :D Now it does work on the server as well. 
but many thanks to you @skeydan !

**Comment by skeydan** [comment]
glad to hear it works now :-)

**Comment by mikechen66** [comment]
msloryg:

I tested a simple keras model on  the Kaggle the leapgestrecog dataset and runned successfully. However, since I changed the simple keras model to the AlexNet model,  it has had the the message: ValueError: Shapes (None, 1) and (None, 10) are incompatible. 

My AlextNet Model includes model.add(Flatten()).  Please help indicate how to correct the issue. 

I am pleased to list the snippet of code and the error messages as follows. 

** 5. AlexNet Model:** 

I truncates the AlexNet model from the 5th Conv Layer to model.summary()
```

......
# 5th Convolutional Layer: (13-3+2*1) + 1 = 13
model.add(Conv2D(filters=256, kernel_size=(3,3), strides=1, 
                 padding='same', activation='relu'))
# Max Pooling: (13-3+2*0)/2 + 1 =  6
model.add(MaxPooling2D(pool_size=(3,3), strides=(2,2), padding='valid'))

# Flatten 256 x 6 x 6 = 9216 as one dimention vector and pass it to the 6th Fully
# Connected layer
model.add(Flatten())

# 6th Fully Connected Layer
model.add(Dense(4096, activation='relu'))
# Add Dropout
model.add(Dropout(0.5))

# 7th Fully Connected Layer
model.add(Dense(4096, activation='relu'))
# Add Dropout 
model.add(Dropout(0.5))

# No.8 FC Layer
model.add(Dense(1000, activation='relu'))
model.add(Dense(num_classes, activation='softmax'))

model.summary()
```

**6.Train the network**

```
for data_batch,label_batch in train_generator:
    print("data batch shape:",data_batch.shape)
    print("labels batch shape:",label_batch)
   
    break

```

data batch shape: (20, 150, 150, 3)
labels batch shape: [4. 3. 2. 0. 3. 9. 9. 5. 5. 6. 6. 5. 9. 0. 7. 6. 8. 6. 9. 9.]

# Tain the model
```
history = model.fit(train_generator,
                    steps_per_epoch=100,
                    epochs=30,
                    validation_data=validation_generator,
                    validation_steps=50)
```

# ---------------------------------------------------------------------------------------------------------------

**Errors message listed as follows.** 

Epoch 1/30

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-bfe902893d62> in <module>
      4                     epochs=30,
      5                     validation_data=validation_generator,
----> 6                     validation_steps=50)

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in _method_wrapper(self, *args, **kwargs)
     64   def _method_wrapper(self, *args, **kwargs):
     65     if not self._in_multi_worker_mode():  # pylint: disable=protected-access
---> 66       return method(self, *args, **kwargs)
     67
     68     # Running inside `run_distribute_coordinator` already.

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py in fit(self, x, y, batch_size, epochs, verbose, callbacks, validation_split, validation_data, shuffle, class_weight, sample_weight, initial_epoch, steps_per_epoch, validation_steps, validation_batch_size, validation_freq, max_queue_size, workers, use_multiprocessing)
    846                 batch_size=batch_size):
    847               callbacks.on_train_batch_begin(step)
--> 848               tmp_logs = train_function(iterator)
    849               # Catch OutOfRangeError for Datasets of unknown size.
    850               # This blocks until the batch has finished executing.

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    578         xla_context.Exit()
    579     else:
--> 580       result = self._call(*args, **kwds)
    581
    582     if tracing_count == self._get_tracing_count():

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    625       # This is the first call of __call__, so we have to initialize.
    626       initializers = []
--> 627       self._initialize(args, kwds, add_initializers_to=initializers)
    628     finally:
    629       # At this point we know that the initialization is complete (or less

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    504     self._concrete_stateful_fn = (
    505         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 506             *args, **kwds))
    507
    508     def invalid_creator_scope(*unused_args, **unused_kwds):

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2444       args, kwargs = None, None
   2445     with self._lock:
-> 2446       graph_function, _, _ = self._maybe_define_function(args, kwargs)
   2447     return graph_function
   2448

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   2775
   2776       self._function_cache.missed.add(call_context_key)
-> 2777       graph_function = self._create_graph_function(args, kwargs)
   2778       self._function_cache.primary[cache_key] = graph_function
   2779       return graph_function, args, kwargs

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   2665             arg_names=arg_names,
   2666             override_flat_arg_shapes=override_flat_arg_shapes,
-> 2667             capture_by_value=self._capture_by_value),
   2668         self._function_attributes,
   2669         # Tell the ConcreteFunction to clean up its graph once it goes out of

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    979         _, original_func = tf_decorator.unwrap(python_func)
    980
--> 981       func_outputs = python_func(*func_args, **func_kwargs)
    982
    983       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    439         # __wrapped__ allows AutoGraph to swap in a converted function. We give
    440         # the function a weak reference to itself to avoid a reference cycle.
--> 441         return weak_wrapped_fn().__wrapped__(*args, **kwds)
    442     weak_wrapped_fn = weakref.ref(wrapped_fn)
    443

~/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    966           except Exception as e:  # pylint:disable=broad-except
    967             if hasattr(e, "ag_error_metadata"):
--> 968               raise e.ag_error_metadata.to_exception(e)
    969             else:
    970               raise

ValueError: in user code:

    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:571 train_function  *
        outputs = self.distribute_strategy.run(
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:951 run  **
        return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2290 call_for_each_replica
        return self._call_for_each_replica(fn, args, kwargs)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/distribute/distribute_lib.py:2649 _call_for_each_replica
        return fn(*args, **kwargs)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py:533 train_step  **
        y, y_pred, sample_weight, regularization_losses=self.losses)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/compile_utils.py:205 __call__
        loss_value = loss_obj(y_t, y_p, sample_weight=sw)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:143 __call__
        losses = self.call(y_true, y_pred)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:246 call
        return self.fn(y_true, y_pred, **self._fn_kwargs)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/losses.py:1527 categorical_crossentropy
        return K.categorical_crossentropy(y_true, y_pred, from_logits=from_logits)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/keras/backend.py:4561 categorical_crossentropy
        target.shape.assert_is_compatible_with(output.shape)
    /home/mike/miniconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py:1117 assert_is_compatible_with
        raise ValueError("Shapes %s and %s are incompatible" % (self, other))

    ValueError: Shapes (None, 1) and (None, 10) are incompatible

**Comment by mikechen66** [comment]
With regard to the  above-mentioned issue,  I have the similar solution as follows. I have already applied it into another AlexNet-based application and runs well. 

Add the one-hot lines of code into the preprocessing of train images  in order to comply with TensotFlow 2.2 and Keras 2.4.3. 

```
    train_images = np.array(train_images)
    train_labels = np.array(train_labels)
    train_labels = utils.to_categorical(train_labels)
```

I think that I can solve the gesture recognition issue.

**Comment by mikechen66** [comment]
I have solve gesture recognition issue with the AlexNet Model. Since the gesture recognition complies with the binary configuration. Therefore, I made the following changes. 

** 5. AlexNet Model:**

## Set the class number as 1 in order to comply with the label (1)
```
num_classes = 1
```

# # Change the activation from softmax to sigmoid

```
model.add(Dense(num_classes, activation='sigmoid'))
```

# Compile the model: change loss from categorical_crossentropy to binary_crossentropy
model.compile(optimizer=tf.keras.optimizers.Adam(0.001),
                        loss='binary_crossentropy',
                        metrics=['acc'])

Cheers
