### ISSUE TITLE
getting gradients

### ISSUE THREAD

**Issue by ivokwee** [rstudio/keras#81]
I am trying to get the value of the gradient (of the weights wrt to the loss) as R matrix. I got so far:

```
K <- backend()
wt <- model$trainable_weights[c(1,3,5)]
gr <- K$gradients(model$total_loss, wt)
dim(K$eval(wt[[1]]))
dim(K$eval(gr[[1]]))
```

K$eval(wt[[1]]) works but the last K$eval(gr[[1]]) throws these errors:

```
2017-07-26 20:40:03.651904: W tensorflow/core/framework/op_kernel.cc:1148] Invalid argument: Shape [-1,4000] has negative dimensions
2017-07-26 20:40:03.651978: E tensorflow/core/common_runtime/executor.cc:644] Executor failed to create kernel. Invalid argument: Shape [-1,4000] has negative dimensions
```

Anyone knows what to do?

Thanks,

Ivo

**Comment by jjallaire** [comment]
The `K$gradients` function is probably returning a tensor with the batch dimension (that's what the -1 is I think). Maybe remove that dimension from the tensor? (see: https://tensorflow.rstudio.com/using_tensorflow_api.html#tensor_extraction)

**Comment by ivokwee** [comment]
I found out in Python we need to do something like this

`gradients = sess.run(gradient_step, feed_dict={x: test})`

what is the syntax in R/Keras?

**Comment by ivokwee** [comment]
OK. I got it. Here is a simple complete example for anyone in future.

```
require(keras)
require(tensorflow)

## simple example
N=200
x <- matrix( sample(1:10,3*N,replace=TRUE),ncol=3)
A <- matrix( sample(1:10,9,replace=TRUE),3,3)
y <- x %*% A
model %>% fit(x, y, epochs=20)

## get gradients
K  <- backend()
wt <- model$trainable_weights
grad <- K$gradients( model$output, wt)[[1]]

sess=K$get_session()
sess$run( grad, feed_dict = dict(input_layer=x) )
```

**Comment by jjallaire** [comment]
Terrific, I was going to come in this morning and try to sort this out, glad you managed to do it first!

**Comment by ivokwee** [comment]
I added a dropout layer but then sess$run gives an error saying I must provide a value in the feed_dict:

`InvalidArgumentError: You must feed a value for placeholder tensor 'dropout/keras_learning_phase' with dtype bool`

How do I do that? I tried this but my syntax seems wrong:

```
sess$run( grad, feed_dict = dict( input_layer=x,
                                 'dropout/keras_learning_phase'=FALSE ))
```

**Comment by jjallaire** [comment]
That will correctly create a dictionary with that as a key, but it seems
that Keras is looking for a different key. I'm not sure what the right
answer is.

**Comment by ivokwee** [comment]
OK. I found the solution. The dict key needs to be (pointer to) a tensor and it is given by K$learning_phase(). So this seems to works:

```
lp <- K$learning_phase()
sess$run( grad, feed_dict = dict(input_layer=x, lp=0))
```

**Comment by jjallaire** [comment]
Great, thanks for letting me know. Glad this is working!

**Comment by ds5j** [comment]
I tried this for a sequential model but it does not appear to work.   The error seems to relate to dimensions as it is excepting the dimensions of hidden layers.

is there a general example of looping through layers to get gradients at the end of each epoch?  I am trying to compute the gradient norm after each batch.

thanks

model <- keras_model_sequential() %>% 
  layer_dense(units = num_hidden_units,input_shape = dim(train_data)[[2]],activation='tanh',
  ) %>%
  layer_dense(units = 1) 

K  <- backend()
wt <- model$trainable_weights
grad <- K$gradients( model$output, wt)[[1]]

sess=K$get_session()
#print(sess$run( grad, feed_dict = dict(input_layer=model$input) ))
sess$run( grad, feed_dict = dict(input_layer=x) )

error in py_call_impl(callable, dots$args, dots$keywords) : 
  InvalidArgumentError: You must feed a value for placeholder tensor 'dense_99_input' with dtype float and shape [?,1]
	 [[Node: dense_99_input = Placeholder[dtype=DT_FLOAT, shape=[?,1],

**Comment by skeydan** [comment]
You need to have a functional model in order to be able to pass it values for the input tensor, as shown in the above example by @ivokwee.

**Comment by ds5j** [comment]
thanks, Switching to functional works.    
One follow up as I am going to use this code in a callback how do I ensure the input to the model is the batch data the model just processed.

As right now the code is passing in my full train_data but in callback I would need a reference to the batch processed.  Does model have a parameter for that?

if I try train_data[[1]]  I get an error but full 20 points of train works:
sess$run( grad, feed_dict = dict(input_layer=train_data[1]) )
 Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: Cannot feed value of shape () for Tensor u'input_1:0', which has shape '(?, 1)' 


## define layers
input_layer <- layer_input(shape = 1, name = 'input')
output_layer <- input_layer %>% layer_dense(units = 100, activation = 'tanh') %>%  layer_dense(units = 1) 
model <- keras_model(inputs = input_layer, outputs = output_layer )

model %>% compile(
  optimizer = 'sgd', 
  loss = "mse", 
  metrics = c("mae")
)
model %>% fit(train_data, train_target, epochs=20,batch_size = 10, verbose = 0)

K  <- backend()
wt <- model$trainable_weights
grad <- K$gradients( model$output, wt)

sess=K$get_session()
#print(sess$run( grad, feed_dict = dict(input_layer=model$input) ))
sess$run( grad, feed_dict = dict(input_layer=train_data) )

**Comment by psc25** [comment]
I have a similar problem (also with Keras in R) and tried to solve as you suggested, but it does not work. 
The code is as follows:
`gr <- k_gradients(NN$output,NN$input)[[1]]`
`sess <- k_get_session()`
`lp <- k_learning_phase()`
`sess$run(gr,feed_dict=dict(input_layer=NN$input,lp=0))`
where NN is the Keras model. It gives me the following error message: 
` Error in py_call_impl(callable, dots$args, dots$keywords) :`
`TypeError: Cannot interpret feed_dict key as Tensor: The name 'input_layer' looks like an (invalid)`
`Operation name, not a Tensor. Tensor names must be of the form "<op_name>:<output_index>".`

I would like to evaluate the gradients inside the loss function and if possible, I would like to calculate the hessian of output wrt. input (gradient of gradient) there. Has anybody an idea? Thanks already.

**Comment by skeydan** [comment]
How did you define the functional model?
The ```feed_dict``` key has to match the value of the ```input``` argument in the ```keras_model``` call.

However, I don't know if you can do that, obtain the gradients inside a loss function.

**Comment by psc25** [comment]
Thanks for your help! The model is defined as follows. d is the dimension of features, n is somehow a time dimension, where on each time step the nerual network is evaluated and M is the sample size, i.e.
x_train is an array of `(sample,timestep,dimension) = (M,n,d)`
y_train is an array of `(sample,timestep,dimension) = (M,n,1)`

```
myloss <- function(input,output,target,additional) {
  gr <- k_gradients(output,input)[[1]]
  sess <- k_get_session()
  lp <- k_learning_phase()
  gr <- sess$run(gr,feed_dict=dict(input_layer=NN$input,lp=0))
  v2 <- k_reshape(input,shape=c(M,n,d,d))
  gr2 <- k_gradients(gr,v2)[[1]]
  z <- k_dot(additional,gr2)
  z <- k_batch_dot(input,z,axes=c(3,4))
  z <- k_batch_dot(z,input,axes=c(3,3))
  z <- k_cumsum(z,axis=1)
  return(K$sum(output+z-target)^2)
}

batch_size <- 50

NN <- keras_model_sequential()
NN %>%
  layer_dense(units = 100, activation = 'relu', input_shape = c(n,d)) %>% 
  layer_dense(units = 100, activation = 'relu') %>%
  layer_dense(units = 1, activation = 'relu')
summary(NN)

NN %>% compile(
  loss = myloss(NN$input,NN$output,k_constant(y_train),k_constant(additional)),
  optimizer = "adam",
  metrics = "acc"
)
history <- NN %>% fit(
  x_train,y_train, 
  epochs = 50,batch_size = batch_size, 
  validation_split = 0.1
)
```
Moreover, the tensor `additional` is of the form `(M,n,d,d)`, just like the second partial derivative of output wrt. input should be. With this setup, the training starts but fails when evaluating `gr <- sess$run(gr,feed_dict=dict(input_layer=NN$input,lp=0))` in the loss function with the error message mentioned above.
I think the problem is the output of `gr` and the input of `gr2`. There are other posts which solved it, but directly in Python and not in R, see [https://stackoverflow.com/questions/49935778/second-derivative-in-keras](url). Do you know, is my goal even possible? Thanks for your help.

**Comment by skeydan** [comment]
Hi,
let's take a simpler example:

```
library(keras)
library(tensorflow)
sess <- k_get_session()

x_train <-
  iris[1:120, c("Petal.Length", "Sepal.Length")] %>% as.matrix()
y_train <-
  iris[1:120, c("Petal.Width", "Sepal.Width")] %>% as.matrix()

input <- layer_input(shape = 2)
output <- input %>%  layer_dense(units = 32, input_shape = 2) %>%
  layer_dense(units = 2)
model <- keras_model(input, output)

gradfunc <- k_gradients(model$output, model$input)[[1]]

someconstants <- k_constant(0.5)
custom_loss <- function(y_true, y_pred, constants) {
  mse <- k_mean(k_square(y_true - y_pred))
  # The value of a feed cannot be a tf.Tensor object.
  # but you don't have access to the input values here, so you can't pass them as scalars
  # grads <- sess$run(gradfunc, feed_dict = dict(input = model$input))
  mse 
}

model %>% compile(
  optimizer = "adam",
  loss = function(y_true, y_pred)
    custom_loss(y_true, y_pred, someconstants),
  metrics = "mse"
)

history <-
  model %>% fit(x_train,
                y_train,
                batch_size = 10,
                epochs = 20)
```

If you want to get the gradients, you have to pass in values, not tensors, so this

``` 
sess$run(gradfunc, feed_dict = dict(input = model$input))
```

will fail but this

```
sess$run(gradfunc, feed_dict = dict(input = x_train[1, , drop = FALSE]))
```

will work.

However, this also means you can't use it in a loss function, because there you don't have access to the input data, just y_true and y_pred. 
(BTW the signature also has to be like that: ```loss(y_true, y_pred)``` and if you want to pass in additional input you have to implement a workaround like shown above.)

(If you didn't work in batches you could probably pass in the complete ```x_train``` . But I guess you wouldn't want to go there).

Looking at the Stackoverflow you linked, this is an excellent solution but for a different problem. 
Or perhaps I misunderstood what you want to do! In the SO example, they want to calculate the Hessian in the loss function not as additional information to be factored in the loss, but as the main thing, to have the network calculate the second (or higher) derivatives.

**Comment by psc25** [comment]
I think I am getting closer to the problem, or at least to the understanding of tensors thanks to your explanations. I changed the inputs to the iris data so that we are talking about the same. My goal would be to penalize the loss function with the second derivative of the neural network.

I see why I can't insert the gradients in the loss function directly and why they can be only calculated afterwards. It would be cool to somehow have access to the input data (or the indices used for the batch) in the loss function that are used for the current evaluation. Therefore, I tried something similar (involving the gradients and not the Hessian so far):
```
library(keras)
library(tensorflow)
sess <- k_get_session()

x_train <-
  iris[1:120, c("Petal.Length", "Sepal.Length")] %>% as.matrix()
y_train <-
  iris[1:120, c("Petal.Width", "Sepal.Width")] %>% as.matrix()

input <- layer_input(shape = 2)
output <- input %>%  layer_dense(units = 32, input_shape = 2) %>%
  layer_dense(units = 2)
model <- keras_model(input, output)

gradfunc <- k_gradients(model$output, model$input)[[1]]
hessfunc <- k_gradients(gradfunc,model$input)[[1]]

custom_loss <- function(y_true, y_pred, input) {
  gr <- k_gradients(y_pred,input)[[1]]
  print(k_shape(gr))
  # gr2 <- k_gradients(gr,input)[[1]] does not work because none values
  # print(k_shape(gr2))
  pen_mse <- k_mean(k_square(y_true - y_pred)) + k_sum(k_abs(gr))
  return(pen_mse)
}

model %>% compile(
  optimizer = "adam",
  loss = function(y_true, y_pred)
    custom_loss(y_true, y_pred, model$input),
  metrics = "mse"
)

history <-
  model %>% fit(x_train,
                y_train,
                batch_size = 10,
                epochs = 20)

grad <- sess$run(gradfunc, feed_dict = dict(input = x_train[1, , drop = FALSE]))
hess <- sess$run(hessfunc, feed_dict = dict(input = x_train[1, , drop = FALSE]))
```

This works so far, but I am not sure if the loss is calculated in the right way, i.e. if the gradients are only calculated for the current batch or for the full input data). On the other hand, what does not work, is the computation of the Hessian - this seems to be more tricky. Perhaps there could be a way to compute the Hessian using Lambda layers (as in the linked Stackoverflow example). Thanks!

**Comment by skeydan** [comment]
That's really cool you figured out how to do it!
I wasn't aware that it'd actually work passing in ```model$input``` as you do.

I would assume everything should work in batches, but you could check "empirically", comparing results with different batch sizes (e.g., 120 for whole dataset and a small number for comparison?)
Or construct an even simpler dataset.

For the hessian, there is a tensorflow function

https://www.tensorflow.org/api_docs/python/tf/hessians

which you can call from R (```tf$hessians```), maybe try that?

**Comment by psc25** [comment]
I was also surprised! And it seems that also the right batch size is used as input in the loss function (I have checked it by multiplying the `y_pred` tensor with the gradient `gr` and I don't get a size error).

However, the evaluation of the Hessian seems to be more tricky (I wasn't aware that tensorflow can be used simultaneously...). If I put `hess <- tf$hessians(y_pred,input)` in the loss function, it returns the error `TypeError: Fetch argument None has invalid type <class 'NoneType'>`.

The code so far:
```
library(keras)
library(tensorflow)
sess <- k_get_session()

x_train <-
  iris[1:120, c("Petal.Length", "Sepal.Length")] %>% as.matrix()
y_train <-
  iris[1:120, c("Petal.Width", "Sepal.Width")] %>% as.matrix()

input <- layer_input(shape = 2)
output <- input %>%  layer_dense(units = 32, input_shape = 2) %>%
  layer_dense(units = 2)
model <- keras_model(input, output)

custom_loss <- function(y_true, y_pred, input) {
  hess <- tf$hessians(y_pred,input)
  pen_mse <- k_mean(k_square(y_true - y_pred)) + k_sum(k_abs(hess))
  return(pen_mse)
}

model %>% compile(
  optimizer = "adam",
  loss = function(y_true, y_pred)
    custom_loss(y_true, y_pred, model$input),
  metrics = "mse"
)

history <-
  model %>% fit(x_train,
                y_train,
                batch_size = 120,
                epochs = 20)
```
Probably this is an error of how the Hessian is implemented (e.g. [https://stackoverflow.com/questions/45396699/tf-hessians-valueerror-none-values-not-supported](url)). Hopefully, I figure it out or perhaps you see it directly. Nevertheless, thanks again for the hint with `tf$hessian`.

**Comment by skeydan** [comment]
The hessian needs a scalar as first input:

> The Hessian is a matrix of second-order partial derivatives of a scalar tensor (see https://en.wikipedia.org/wiki/Hessian_matrix for more details).

This here seems to work fine - at least syntactically - you might want to check if it gives the desired results:

```
library(keras)
library(tensorflow)
sess <- k_get_session()

x_train <-
  iris[1:120, c("Petal.Length", "Sepal.Length")] %>% as.matrix()
y_train <-
  iris[1:120, c("Petal.Width", "Sepal.Width")] %>% as.matrix()

input <- layer_input(shape = 2)
output <- input %>%  layer_dense(units = 32, input_shape = 2) %>%
  layer_dense(units = 2)
model <- keras_model(input, output)

custom_loss <- function(y_true, y_pred, input) {
  loss <- k_mean(k_square(y_true - y_pred))
  hess <- tf$hessians(loss,input)
  pen_mse <- loss + k_sum(k_abs(hess))
  return(pen_mse)
}

model %>% compile(
  optimizer = "adam",
  loss = function(y_true, y_pred)
    custom_loss(y_true, y_pred, model$input),
  metrics = "mse"
)

history <-
  model %>% fit(x_train,
                y_train,
                batch_size = 120,
                epochs = 1)

```

**Comment by psc25** [comment]
Sorry I was confused - the problem was our 2-dimensional target used as output, so I changed to 1 dimension for `y_train` and 3 dimensions for `x_train`. Then, it worked fine.  Now, there is one step left to achieve my goal: I would like to pertubate the Hessian in the loss function by a constant matrix called `additional` which is defined before (here randomly generated). Of course, I have now a dimensional problem in the element-wise multiplication, because `hess` is of shape `(NULL,3,NULL,3)` and `additional` is of shape `(120,3,120,3)`. The code:
```
library(keras)
library(tensorflow)

x_train <-
  iris[1:120, c("Petal.Length", "Sepal.Length","Petal.Width")] %>% as.matrix()
y_train <-
  iris[1:120, c("Sepal.Width")] %>% as.matrix()
addit <- array(rnorm(129600),dim=c(120,3,120,3))
additional <- k_constant(addit)

input <- layer_input(shape = 3)
output <- input %>%  
  layer_dense(units = 32, input_shape = 3, activation = "relu") %>%
  layer_dense(units = 1)
model <- keras_model(input, output)

custom_loss <- function(y_true, y_pred, input) {
  hess <- tf$hessians(y_pred, input)[[1]]
  print(k_shape(hess))
  print(k_shape(additional))
  hess_per <- k_batch_dot(additional,hess,c(4,4))
  pen_mse <- k_mean(k_square(y_true - y_pred)) + k_sum(k_abs(hess_per))
  return(pen_mse)
}

model %>% compile(
  optimizer = "adam",
  loss = function(y_true, y_pred)
    custom_loss(y_true, y_pred, model$input),
  metrics = "mse"
)

history <-
  model %>% fit(x_train,
                y_train,
                batch_size = 20,
                epochs = 20)
```
Is there a possibility to take the indices of the current batch into account in order to choose the right values of `additional` for the multiplication? I have tried it already by using the other keras function `k_batch_dot` and by passing `additional` as additional argument to the loss function. The latter didn't work at all. Thanks again.

**Comment by skeydan** [comment]
yet another thing that came to mind: if you use tensorflow eager execution, as described here

https://blogs.rstudio.com/tensorflow/posts/2018-08-26-eager-dcgan/

and here

https://blogs.rstudio.com/tensorflow/posts/2018-07-30-attention-layer/

you can implement any custom loss you want :-)

**Comment by psc25** [comment]
The idea of several inputs is brilliant - I have to consider that and think about to implement in this case. However, I have tried the following inside the loss function:
```
custom_loss <- function(y_true, y_pred, input) {
  hess <- tf$hessians(y_pred, input)[[1]]
  cond <- tf$equal(k_repeat(input, N), k_reshape(k_repeat(xtr, batch_size), c(batch_size, N, d)))
  ind <- tf$where(tf$reduce_all(cond, axis=2L))[, 2]
  add2 <- tf$gather(tf$gather(additional, ind, axis = 0L), ind, axis = 2L)
  hess_per <- tf$multiply(add2, hess)
  pen_mse <- k_mean(k_square(y_true - y_pred)) + k_sum(k_abs(hess_per))
  return(pen_mse)
}
```
But the problem is that the `batch_size` is apparently not the same in all compiling evaluations (sometimes zeros and sometimes multiples of it). Therefore, the use of `k_zeros_like` as in your links could be interesting (e.g. for `cond`) and then the right values could be fed into the tensor.

**Comment by skeydan** [comment]
Hi,

I'm still thinking that _in principle_, this should be a perfect use case for eager execution... because of the freedom you have implementing things.
Unfortunately it seems that `tf.hessians` is not supported (see the error message you get if you uncomment the respective line below).

So it would need some more research, and I can't even guarantee it is at all feasible - but if you're feeling adventurous or even just for documentation and possibly later usage, I'm putting here the code for your basic example (with no Hessian, just MSE).

In contrast to the "classical" ways, here you see how you can get much more debugging info (just print things out).

```
library(keras)
use_implementation("tensorflow")

library(tensorflow)
tfe_enable_eager_execution(device_policy = "silent")

library(tfdatasets)

x_train <-
  iris[1:120, c("Petal.Length", "Sepal.Length", "Petal.Width")] %>% as.matrix()
y_train <-
  iris[1:120, c("Sepal.Width")] %>% as.matrix()

dataset <- tensor_slices_dataset(list (x_train, y_train)) %>%
  dataset_batch(10)

n_epochs <- 5

create_model <- function(name = NULL) {
  keras_model_custom(name = name, function(self) {
    self$dense1 <- layer_dense(units = 1)
    
    function (x, mask = NULL) {
      self$dense1(x)
    }
  })
}

model <- create_model()

custom_loss <- function(y_true, y_pred, x) {
  mse <- tf$losses$mean_squared_error(y_true, y_pred)
  # not compatible with eager execution
  # hess <- tf$hessians(y_pred, x)
  mse
}

optimizer <- tf$train$AdamOptimizer()



for (i in seq_len(n_epochs)) {
  
  iter <- make_iterator_one_shot(dataset)
  total_loss <- 0
  
  until_out_of_range({
    batch <-  iterator_get_next(iter)
    x <- batch[[1]]
    y <- batch[[2]]
    
    with(tf$GradientTape() %as% tape, {
      preds <- model(x)
      #print(preds)
      loss <- custom_loss(y, preds, x)
    })
    
    total_loss <- total_loss + loss
    gradients <- tape$gradient(loss, model$variables)
    #print(gradients)
    
    optimizer$apply_gradients(
      purrr::transpose(list(gradients, model$variables)),
      global_step = tf$train$get_or_create_global_step()
    )

  })
  
  cat("Total loss (epoch): ", i, ": ", total_loss$numpy(), "\n")
}

```

**Comment by psc25** [comment]
Hi, it took me a while until I could get back to the problem. I have found a new interesting idea: By appending the additional term to `y_train`, it is passed in the right batch sizes to the custom loss function. Then, it finally works! For completeness, the loss function is in this case given by
```
myloss <- function(y_true,y_pred,input) {
  y_split <- tf$split(y_true,c(1L,as.integer(d^2)),2L)
  y_tr <- y_split[[1]]
  add <- y_split[[2]]
  hess <- tf$hessians(y_pred,input)[[1]][,,,1,1,]
  sh <- k_shape(hess)
  hessp <- tf$multiply(k_reshape(add,sh),hess)
  err <- k_sum(k_square(y_pred-y_tr))+k_sum(k_abs(hessp))
  return(err)
}
```
Before, the term for the permutation of the Hessian has to be appended to `y_train` by using for example first `array_reshape` (to have the same dimension as `y_train`) and then `abind` (to append).

**Comment by skeydan** [comment]
Thanks, great to hear you got it to work!
And thanks for sharing the code.
