### ISSUE TITLE
8.3.3 Neural style transfer in Keras

### ISSUE THREAD

**Issue by GreyMerchant** [rstudio/keras#828]
Hello, 

I have been working through the examples in the book and I was wondering how to get the output as a 1200 x 1200. Both my target image and style image are each 1200 x 1200. I have changed all the relevant fields and yet I am still producing an output image that is far smaller than 1200 x 1200. 

```
library(keras)

# This is the path to the image you want to transform.
target_image_path <- "xxx"

# This is the path to the style image.
style_reference_image_path <- "xxx"

# Dimensions of the generated picture.
img <- image_load(target_image_path)
width <- img$size[[1]]
height <- img$size[[2]]
img_nrows <- 1200
img_ncols <- as.integer(width * img_nrows / height)
```
img_ncols  returns 1200L while similarly width and height also returns the same value. 

I have also changed the final values within as.raster (it wasn't part of the code but that was the only other thing I could think about). 

```
iterations <- 5

dms <- c(1, img_nrows, img_ncols, 3)

# This is the initial state: the target image.
x <- preprocess_image(target_image_path)
# Note that optim can only process flat vectors.
x <- array_reshape(x, dim = length(x))  

for (i in 1:iterations) { 
  
  # Runs L-BFGS over the pixels of the generated image to minimize the neural style loss.
  opt <- optim(
    array_reshape(x, dim = length(x)), 
    fn = evaluator$loss, 
    gr = evaluator$grads, 
    method = "L-BFGS-B",
    control = list(maxit = 15)
  )
  
  cat("Loss:", opt$value, "\n")
  
  image <- x <- opt$par
  image <- array_reshape(image, dms)
  
  im <- deprocess_image(image)
  plot(as.raster(im, nrow = 1200, ncol = 1200))
```

I am missing another location where I need to change this? Does this have something to do with what VGG19 was originally trained on? 

(also for context - I am running this on a GPU (RTX 2080 TI) so I think I am at least in the clear there in terms of requirement)

As always any help would be appreciated :)

**Comment by dfalbel** [comment]
Do you see any errors? What happens when you run this code?

**Comment by GreyMerchant** [comment]
Hello, 

No errors in the running aside from TF saying: "Allocator (GPU_0_bfc) ran out of memory trying to allocate 2.40GiB. The caller indicates that this is not a failure, but may mean that there could be performance gains if more memory were available."

The uploaded image is my output and my input images are definitely 1200 x 1200 as .jpg (both the style and image on which to transfer)


![00000a](https://user-images.githubusercontent.com/39332355/60681056-094b8680-9e8e-11e9-954c-34eef760745d.png)

**Comment by Lauler** [comment]
1200x1200 sounds ambitious. The maximum I could do with my 2080 Ti was 512x512. 

One thing that makes image output smaller than expected from that tutorial is that R tends to plot images with margins (white borders around the sides of the image). 

A suggestion would be to add `par(mar=c(0, 0, 0, 0))` in order to eliminate the margins that R adds to saved images:

```
if (i %% 100 == 0) {
        png(paste0("style_epoch_", i, ".png"))
        plot_image <- best_image$numpy()
        par(mar=c(0, 0, 0, 0))
        plot_image <- deprocess_image(plot_image)
        plot(as.raster(plot_image), main = glue("Iteration {i}"))
        dev.off()
      }
```

**Comment by GreyMerchant** [comment]
> 
> 
> 1200x1200 sounds ambitious. The maximum I could do with my 2080 Ti was 512x512.
> 
> One thing that makes image output smaller than expected from that tutorial is that R tends to plot images with margins (white borders around the sides of the image).
> 
> A suggestion would be to add `par(mar=c(0, 0, 0, 0))` in order to eliminate the margins that R adds to saved images:
> 
> ```
> if (i %% 100 == 0) {
>         png(paste0("style_epoch_", i, ".png"))
>         plot_image <- best_image$numpy()
>         par(mar=c(0, 0, 0, 0))
>         plot_image <- deprocess_image(plot_image)
>         plot(as.raster(plot_image), main = glue("Iteration {i}"))
>         dev.off()
>       }
> ```

Hello Lauler, 

Thank you for your reply :) I didn't think it would be that ambitious given for a 2080 TI but I was obviously wrong! I definitely am still learning the limits and I haven't done as much work with image data yet. I am sure this just gets worse as you go into 5D tensors etc. 

So if I understand you correctly and the error above, you can only manage far larger images by having far more memory in the card? Is there no way to potentially do half precision here and double the memory for this?

**Comment by Lauler** [comment]
It is indeed the memory which limits the size.  Nvidia unfortunately didn't increase the memory from the previous generation of cards. I can't give a good answer about precision because I haven't experimented with it myself. But your card should in theory be able to train mixed precision networks.

The people who produce high resolution images from style transfer algorithms generally use a multi-GPU setup. If you are interested in learning more I suggest going to the /r/deepdream community on reddit and asking questions there:

https://www.reddit.com/r/deepdream/

In particular the moderator/user ProgamerGov helps out a lot.
https://www.reddit.com/user/ProGamerGov/

Unfortunately they tend to use ready made scripts written in Torch/PyTorch. So it's difficult to use R if you intend to try multi-GPU neural style transfer.
